### ISSUE TITLE
Add sprites to atlas generator

### ISSUE THREAD

**Issue by SolsticeSpectrum** [runi95/turtle-control-panel#15]
Since atlas generator can already display most of the world, it would be nice to have the same for items

**Comment by runi95** [comment]
Definitely agree with this, would be great to have the generator create both texture atlas (as it does today) **and** a sprite atlas as well!

**Comment by runi95** [comment]
Ran into quite a few issues with this one, especially trying to run gl in a Node backend without node-gyp (due to how many issues people have with node-gyp in general).
I ended creating a separate portal for the asset-generator that let's you import assets because gl can always be used in a browser environment.
