### ISSUE TITLE
Add 3D world view 

### ISSUE THREAD

**Issue by DarkReaper231** [runi95/turtle-control-panel#6]
Similar to projects like turtle gambit:
https://github.com/ottomated/turtle-gambit

Or this project:
https://github.com/SpaceCat-Chan/Computercraft-Websocket-Controller

It would be nice to have a 3D world view. But the method those two projects use is not very efficient. They scan the blocks around. It is fine if you can't be physically present but takes a lot of time if you want detailed info.

I recommend the ability to load world data as well as the scanning method as fallback. This way the user can have detailed world view if they can use World Downloader but still be able to to scan the world if they can't get world data.

**Comment by runi95** [comment]
1. I've thought about making a 3D view for this before and very well might make this at some point.
2. For the world downloader I think it sounds useful, but I'm not too fond of the idea because it relies on people having to have external access to the world data in one way or another, which you generally won't have unless you're the server owner. That said it is still very much possible for you (or anyone else really) to create another tool that extracts world data (either from local files or from the world seed) and uploads it to the SQLite database.
Otherwise I recommend using the advanced peripherals scanner which this project supports out of the box.

**Comment by runi95** [comment]
![Screenshot 2024-02-17 at 12-08-00 TCP](https://github.com/runi95/turtle-control-panel/assets/4856656/06edcf6c-64ad-4de5-b0a3-8478d1e77aa4)

Potentially looking at something like this here.
Just not sure if we really need the 2D and 3D view visible at the same time.

**Comment by DarkReaper231** [comment]
This is actually really good

**Comment by DarkReaper231** [comment]
Also it would be nice if we could render turtles in the 3D view based on their position. Basically if the manual reproduction was added as stated in the other issue, it would know the origin position of the turtle. In case of some hiccups possibly due to someone moving the turtle with a piston or something, a manual override should be present too. And if manual override happens, it should also correct and shift blocks scanned by that turtle.

**Comment by runi95** [comment]
Haven't had a chance to work on this for a good while until now, but I've implemented a textured 3D world view and linked a PR this issue with a working concept you might be interested in checking out.

**Comment by DarkReaper231** [comment]
@runi95 that's so cool. Good job! I also mentioned other ideas in the commenrs. Like seeing the turtle itself and if reproduction is added, syncing world view between them. Since the reproduced turtle starts from known position, we can track where it is related to the world. A manual coords adjustment option would be also nice in case a desync happens. There would be couple misplaced blocks in such case but it would prevent from getting more.

**Comment by runi95** [comment]
The turtles already have a synced world view. After creation you're going to have to either manually provide the new turtle with a position + direction or you'll have to provide it with a Wireless Module and use the "Locate" function from the peripherals menu. The turtles can't move if they don't know their location + direction and all movement is tracked in a global system so if you scan the world with Turtle 1 then Turtle 2, 3 and 4 will also see the same blocks as Turtle 1.
It's a bit more work than just pressing a "reproduce" button, but I think that button would be too niche for the majority of users.

**Comment by DarkReaper231** [comment]
That's pretty cool, I'll test it on a server and report back with findings.

**Comment by DarkReaper231** [comment]
@runi95 also what about importing worlds? Two ideas. Importing worlds as zip files or schematics but huge schematics are pain

**Comment by runi95** [comment]
Since I'm using a basic SQLite setup it's very much possible and fairly easy to integrate with the controller.

If you just want to export / import worlds that have been created by the controller you can do so with a any SQLite editor.

If you're talking about imports from Minecraft itself then I probably won't do it as I don't think most players will have access to the world saves directory and thus won't be able to use that feature. That being said it would be very easy for someone to make a thirdparty tool that simply extracts the Minecraft world save data from the saves directory and imports them into the SQLite database. So if you or anyone else wants to try to make that tool I'd be more than willing to help out.

**Comment by DarkReaper231** [comment]
If you tell me what is the data structure, I can spin up a quick Fabric mod

**Comment by runi95** [comment]
The world is stored in the database as individual blocks. The DB blocks type is defined [here](https://github.com/runi95/turtle-control-panel/blob/master/server/src/db/block.type.ts).

The `state` field is something I get from the Geo Scanner and seems to always be `NULL` or an empty JSON object (`{}`) so no clue what it truly holds. This field can safely be ignored for now.

The `tags` field contains block tags data which I haven't used yet and might not ever end up using, but it's something I get from the Geo Scanner and it looks like this for `minecraft:sand`:
```
{
   "minecraft:mineable/shovel":true,
   "minecraft:lush_ground_replaceable":true,
   "forge:sand/colorless":true,
   "minecraft:azalea_root_replaceable":true,
   "minecraft:smelts_to_glass":true,
   ...,
 }
```

Essentially for a usable world import you need to import these columns:
- `serverId` - Which server should the control panel associate the world blocks with?
- `x` - Block x-coordinate
- `y` - Block y-coordinate
- `z` - Block z-coordinate
- `name` - Block full name, ex: minecraft:wall_torch or minecraft:cobblestone
- `state` - Always `NULL`
- `tags` - Always an empty JSON object  (`{}`)
